### ISSUE TITLE
CSRF Token error an ongoing problem on the whispers beta site (EROS)

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#234]
The CSRF token error is a persistent issue on the whispersbeta site, and is currently preventing the creation of an eventgroup. Is this an issue I need to address on the client end, or is the solution within Django? When you have a chance, we should talk more about this.

**Comment by aaronstephenson** [comment]
Nothing new to report here. Workaround is to not be logged in to the Browsable API while using the WHISPers web client.
