### ISSUE TITLE
Include eventlocation comments within the root level comments array on eventdetails response

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#278]
NWHC has requested a more easily sortable comments interface which aggregates all the comments for an event in one table (event-wide comments and the eventlocation comments). Our current eventdetails response has the event record associated comments in array at root level, and the comments for each event location nested respectively within each one. This made sense for the design at the time, but now we will need to also include the eventlocation comments within the root level comments array. We already have the `content_type_string` as a field in the comment record response, which is helpful for identifying event-wide vs location specific comments, and it should remain. But in the root level comment array we will need a way to identify which location those location-specific comments belong to.

The two fields needed for that are `id` and `name`. 

For now, let's leave the eventlocation comments array right where it is, because NWHC may still wish to maintain the simpler comment view at eventlocation level, and removing it would be a breaking change.

**Comment by aaronstephenson** [comment]
As discussed IRL:
- I will create a new field at the root level to combine the two comments lists, named "combined_comments"
- To support date sorting I will include a computed field named "date_sort" as a datetime, where the time portion will indicate the the within-day creation order: "2019-09-04 00:00:01" then "2019-09-04 00:00:02", etc
- The "all_comments" field will be sorted descending (newest first) by "date_sort" by default.

**Comment by aaronstephenson** [comment]
Implemented in 1.3.0 dec18a6

**Comment by aaronstephenson** [comment]
Ordering implemented in 1.3.1 e2ac75c

**Comment by aaronstephenson** [comment]
Haven't heard anything more about this, closing.
