### ISSUE TITLE
adding undetermined if create a complete event

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#280]
I created an event (200201) that I marked as complete within the create event page. Still on the create event page, I selected botulism type c as the event level diagnosis. I hit save. When I went back to look at the event on the event details page, both botulism type c AND undetermined were listed as event diagnoses. I think the undetermined got auto added since the event was marked as complete but it wasn't necessary because I had bot type C there. Undetermined should only kick in if it's been pulled up from the species level, or if there's nothing else indicated at the event level when the event is marked as complete. On the event details page, I hit edit event, marked as incomplete, then the undetermined went away. I can then set it to complete again on the event details page and it doesn't re-add undetermined (which is great).

Was able to recreate this within the test site.

**Comment by BlakeDraper** [comment]
Transferred here form front-end repo. Just another very specific series of actions not yet anticipated.

**Comment by aaronstephenson** [comment]
Sounds like it's just the timing of the checks causing this. Should be a quick fix.

**Comment by aaronstephenson** [comment]
Fixed in 1.3.2 26df3d1
