### ISSUE TITLE
can't add event org

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#281]
I am signed in as jchipault on the live site and am trying to add an event organization to 200194 of San Fransisco Bay NWR Complex. When I try to do that, I get: Error. Event organization not added. Error message: {"detail":"You do not have permission to perform this action."}

Why would I not be able to write to that field?

I was able to delete the org that was there (NWHC) but can't add any orgs.

I was able to add and delete a location comment just fine.

**Comment by BlakeDraper** [comment]
Transferred from front-end repo. Sounds like maybe a small permissions anomaly?

**Comment by aaronstephenson** [comment]
Found the bug. I didn't put a `return` keyword in the code block checking for create permissions, so it comes back False for everyone. Quick and easy fix.

**Comment by aaronstephenson** [comment]
Fixed in 1.3.2 26df3d1
