### ISSUE TITLE
User account upgrade request data schema addition

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#289]
For the user account notification NWHC wants:

I am thinking what we need to add to the data schema is a table for account upgrade requests (with field for comment or attached comment from comment table). These would be deleted once they have served their purpose. Currently, a user can create an account without intervention at the Public role. They can also at the same time request an upgrade to a privileged role. Where this is currently just an email, we would need to instead create a request record which can then be responded to by WHISPers staff on the admin dashboard. This also means that when they approve or deny it, we can update status of the request and notify the upgraded user. We will then need to delete the request record.

Alternatively: We add a single field to the user table that contains an object for upgrade request that contain the role ID requested, status, and a comment string field. We simply null that field out when the request has been denied or satisfied. That may pollute the user table too much though. This would also require a special view so that there is a requests list to pull from to show the WHISPers admins. 

Open to other suggestions and discussion. 

![image](https://user-images.githubusercontent.com/6978380/66490633-15d81000-ea77-11e9-8110-1900d0cc34ad.png)

**Comment by aaronstephenson** [comment]
@BlakeDraper What do you think about just using the existing ServiceRequest model, and just adding a new type to the ServiceRequestType table named something like "User account change" (or perhaps "User Role Change" would be more exact)? This fits almost exactly the workflow for that model: user makes a request the admins, an email is sent, then admins respond. The only change I would need to make on the back end is handling the update notification/email for the SR creator, but I would have to do that regardless.

I suppose we would need some way to handle which role the user is requesting. It could just be in the body of the comment, if we wanted to fit the current ServiceRequest model. Or perhaps a related table that is only used when the ServiceRequestType is "User Role Change", and which isn't exposed as its own endpoint, simply an optional field... tho not sure how I would implement that, exactly.

Or we just go with your first proposal, and I create a new model for this, and just inherit from the existing ServiceRequest model and add a "role_requested" field or something.

**Comment by BlakeDraper** [comment]
From discussion IRL: We will create a 1:1 related model for user account upgrade request. This has the bonus of providing a user account upgrade history that can be accessed easily.
