### ISSUE TITLE
New models for notifications subsystem

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#290]
Per discussion, we will add 4 new models to support the notifications subsystem:

- `NotificationPreferences`
- `NotificationCustomTriggers`
- `NotificationStandardTriggers`
- `NotificationStandardTypes`

---
`NotificationPreferences`: 1:1 with `NotificationStandardTriggers` and `NotificationCustomTriggers` to capture the preference for each trigger.

| ID | new | modified | email |
|----|------|----------|-------|
| 1 | true | true | false |
| 2 | true | false | false |

---
`NotificationCustomTriggers`: Contains the user ID and the value of the custom trigger in a field in JSON

| ID | User ID | eventlocation_administrativelevelone | eventlocation_land_ownership | speciesdiagnosis_diagnosis | species | event_number_affected | event_id |
|----|---------|-------------------------------------------|------------------------------------|---------------------------------------|---------|-----------------------|----------|
| 1 | 39 | {"values": [11,27,39], "operator": "AND"} | {"values": [2], "operator": "AND"} | null | null | null | null |
| 2 | 46 | null | {"values": [3], "operator": "AND"} | {"values": [345], "operator" : "AND"} | null | null | null |

---
`NotificationStandardTriggers`: Each of 4 types is created for every single user (hence the 'standard')

| User ID | type |
|---------|------|
| 53 | 1 |
| 53 | 2 |
| 53 | 3 |
| 53 | 4 |
| 54 | 1 |
| 54 | 2 |
| 54 | 3 |
| 54 | 4 |

---
`NotificationStandardTypes`: The 4 possible types of standard triggers every user has

| ID | Name |
|----|---------------|
| 1 | Own |
| 2 | Org |
| 3 | Collaborating |
| 4 | All |

**Comment by BlakeDraper** [comment]
Updating with a 5th model: the one that contains the actual Notifications themselves which will be queried by user and loaded up for user after login. Seems simple enough to just call that `Notifications`. 

Proposed fields:

`id`: integer
`user`: integer - user id of recipient
`source`: string - string describing source/trigger of the notification, such as a user who added the thing, a Custom Notification, or Standard Notification
`event`: integer - the id of the event the notification pertains to. this will also be in the message string, but having it as its own field facilitates the linking within the client
`read`: boolean - field for marking as read/unread
`link`: string - can debate this one - most of the notification will link the user to an event details page, but some will take them to user dash.  this field would contain that bit of information to facilitate the frontend UI. for now, just a string of either 'event' or `userdashboard`. not sure we would need a separate model for this one.
`message`: string  - the actual message string, taken from the templates model
`created_date`: string
`created_by`: string  - was assuming we would include the standard history model, but begs the question what this field would have since all notification records will be created by the system
`modified_date`: string
`modified_by`: string - ditto

example:

| id | user | source | event | link | read | message | created_date | created_by | modified_date | modified_by |
|----|------------|--------------|-------|-------|-------|----------------------------------------------------|--------------|------------|---------------|-------------|
| 1 | jchipault | "Mark Adams" | 17603 | event | false | "Mark Adams has added a species to Event 17603." | "2019-10-09" | admin | "2019-10-09" | admin |
| 2 | nbaertlein | "Barb Smith" | 17517 | event | false | "Barb Smith has added a diagnosis to event 17517." | "2019-10-07" | admin | "2019-10-07" | admin |

and the JSON:
{
  "id": 0,
  "user": 0,
  "source": "",
  "event": 0,
  "read": false,
  "link": "",
  "message": "",
  "created_date": "",
  "created_by": "",
  "modified_date": "",
  "modified_by": ""
}

**Comment by aaronstephenson** [comment]
Just an idea for discussion: do we need the `user_id` fields for the notification triggers/cues? I'm thinking we could just use `created_by`, like we do for permissions and 'ownership', since the user is literally creating the trigger/cue (explicitly in the case of custom, and implicitly in the case of standard).

And for the notification table, we wouldn't need the `user` field because we wouldn't have use the ID of the `admin` user to create the records (which as you point out makes it a pretty much redundant field), instead using the ID of the particular user that the notification is being created for. Or do you think we need to indicate that the 'system' is doing the creation of the notifications in response to the user's triggers/cues?

**Comment by BlakeDraper** [comment]
I was thinking we would need the user id which serves as the recipient id for querying the notifications that belong to a specific user on login. I suppose we could just use `created_by` for that, but what I don't quite like about that is 1) (I think) we are not using that field which is part of the history model for any actual relations and unsure of any unforeseen issues there even if nothing more than a confusing departure from convention 2) we have been following an implicit convention that `created_by` is for when a user directly creates that record, and in this case the user never directly creates the actual notification record.

**Comment by aaronstephenson** [comment]
OK, thanks. We are using `created_by` in relations, though. Not in the front end perhaps, but all over the place in the back end.

I'm fine with keeping the `user` field in the `notification` model if that makes things clearer, but then I would recommend we change the field name to `recipient`.

**Comment by BlakeDraper** [comment]
Ok, so I retract my point 1 about `created_by`, and using a `recipient` field works for me, but I'm still unsure about saying the notification record was created by a user. I also have no workable alternative, so I say we proceed for now!

**Comment by aaronstephenson** [comment]
Oh, sorry, I didn't respond to that particular point. I meant to say that for `notification` I'm fine with the creator being `admin`.

**Comment by BlakeDraper** [comment]
Would you like to drop the `link` field? Based on a comment in Slack, seemed like you were thinking of making the existence of an event ID implicit to whether the client should link a user to the event or not. My only thought was the `link` field could future proof, because while currently we only foresee linking to either the event or the user dashboard, there could be others in the future (like maybe event creation, or to a specific tab within the userdash).

**Comment by aaronstephenson** [comment]
That's a good point. What if we made `notification` a generic relation like `comment`? Then we could directly link a notification to any other model.

**Comment by BlakeDraper** [comment]
Well, I think that may be overkill. I don't think we necessarily need to relate a notification to a record. 98% of them will just link to an event. The other cases I imagine would not even be a database record, just linking to an area of the app.

**Comment by aaronstephenson** [comment]
Implemented in `notifications` branch 83d68c4

Here are the models I wrote:
(all of them will include the standard fields of id, created_date, created_by, modified_date, and modified_by)


**Notification**
- recipient (User ID of person receiving the notification)
- source (Char, 128 max)
- event (FK to Event model, nullable)
- read (Char, 128 max)
- client_page (string, with options of 'event' or 'userdashboard')
- message (Text, unlimited)


**NotificationCuePreference**
(these are all Boolean with 'fall back' default of True, tho the actual default will be set elsewhere in the code (not directly in the field definition))
- create_when_new
- create_when_modified
- send_email


**NotificationCueCustom**
- notification_cue_preference (1:1 FK to NotificationCuePreference)

(the rest are all nullable JSON fields with a standard format of `{"values": [11,27,39], "operator": "AND"}`)
- event
- event_affected_count
- event_location_land_ownership
- event_location_administrative_level_one
- species
- species_diagnosis_diagnosis


**NotificationCueStandard**
- notification_cue_preference (1:1 FK to NotificationCuePreference)
- standard_type (FK to NotificationCueStandardType)


**NotificationCueStandardType**
- name (Char, 128 max)


For any foreign key field (e.g,. recipient), I can also return additional data from the related object in addition to the ID with the serializer (e.g., recipient_username or recipient_last_name, etc)
