### ISSUE TITLE
Add the creator details to the servicerequest record of the eventdetails response

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#291]
Need these helper fields that are already present on the servicerequest comments:

`created_by`, `created_by_string`, `created_by_first_name`, `created_by_last_name`, `created_by_organization`, `created_by_organization_string`

related: https://github.com/USGS-WiM/whispers/issues/725

**Comment by aaronstephenson** [comment]
Implemented in 1.3.11 28e79ff
