### ISSUE TITLE
Auto-generate a comment when a service request response is updated

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#293]
Per request (and after some discussion) from NWHC (https://github.com/USGS-WiM/whispers/issues/727), please implement the creation of a comment that captures the request response and attach it to the service request record. The comment text should be as follows:

"Service Request Response: [string value of response]"

**Comment by aaronstephenson** [comment]
@BlakeDraper Would this include the automatic "Pending" response upon a Service Request create?

**Comment by BlakeDraper** [comment]
No

**Comment by aaronstephenson** [comment]
Implemented in 1.4.0 aa9637a
