### ISSUE TITLE
Update to notification templates schema: short and long

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#325]
May not be a structural change, perhaps only field naming - we will have two text fields for every notification template:
- Short form / email subject : plain text with variables. Short, one or two sentences. Max character limit  of 128, with a soft limit/suggested length of 78

- Long form / email body: rich text (HTML) with variables. Can be long and split into paragraphs for readability. Max character limit of 5000. 

As for field names, open to discussion, but maybe just `short` and `long`?

**Comment by aaronstephenson** [comment]
Implemented in 1424d5ed

**Comment by aaronstephenson** [comment]
Not pushed to dev server yet
