### ISSUE TITLE
CA certificate bundle error on dev server

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#328]
@aaronstephenson I was testing bulk upload on the `events` endpoint and came across a certificate error on dev server:

![image](https://user-images.githubusercontent.com/6978380/73090582-3ef1a480-3e9e-11ea-924b-43150f9d9b72.png)

looks like a bad path or the missing file. I could probably fix this myself, but is there anything I need to know (before I dig and trial/error myself)

**Comment by aaronstephenson** [comment]
This was resolved, just a missing file.
