### ISSUE TITLE
Implement ability to bulk update notification records

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#332]
For now this will only be used to update the `read` boolean to true or false - for selecting a group in the display table and marking as read or unread.

**Comment by BlakeDraper** [comment]
We should also add to this the ability to bulk delete. Same workflow as described above.

**Comment by aaronstephenson** [comment]
Implemented in 17f3a3a

**Comment by BlakeDraper** [comment]
@aaronstephenson I tried trial/erroring to determine the details using our slack conversation, but no dice

- what is the custom action name (words for URL)
- what are the action name options?
- POST or PATCH?

**Comment by BlakeDraper** [comment]
Ok I got the custom action name from the browseable API - `bulk_update`

**Comment by BlakeDraper** [comment]
figured out the rest with more trial/error
