### ISSUE TITLE
Can't create/register account

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices_django#335]
We're getting an error when a new user is attempting to register as a Natural Resource Professional.  See below.  No account is created.  First reported yesterday 2/12/20.

Browser: Chrome

Values attempted:
username: nkudla
firstname: Nathan Kudla
email: nkudla@contractor.usgs.gov
password: BlackSparrow!123
role: manager
org: NWHC
comment: [left blank]

![image](https://user-images.githubusercontent.com/38669574/74470116-85b23900-4e63-11ea-9262-c8999363a638.png)

**Comment by aaronstephenson** [comment]
This is a back end bug. I'm working on the fix right now.

**Comment by aaronstephenson** [comment]
This is fixed. The code was looking for a specific name in the templates table, but the template it needed had a different name in the test database than in the dev database. Just needed to update the name in the test database.
