### ISSUE TITLE
Discussion: string representation of custom notification cue from server?

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#337]
I am currently working on the front end for the custom notification cues and had a thought for discussion. Assuming we are sticking with this basic construction of the custom cues response,  with each parameter as a JSON object:

```
{
    "new_notification_cue_preference": null,
    "event": null,
    "event_affected_count": null,
    "event_location_land_ownership": null,
    "event_location_administrative_level_one": null,
    "species": null,
    "species_diagnosis_diagnosis": null,
    "created_date": null,
    "created_by": null,
    "modified_by": null
}
```

The client will need to construct a string representation of the cue like so:

![image](https://user-images.githubusercontent.com/6978380/75164510-89a54d00-56e6-11ea-8a4f-df155e19e242.png)

This could be done on the client, of course, but I wonder if it would be more efficient for the overall system for the API to compose that string as a fairly simple byproduct of creating the cue record? Then it would just be a field in the cue record and plugged right into display. 

Depending on how you feel about this, I may suggest a slightly advanced string field which actually puts each parameter's representation in a separate string in an array of strings. The reason for that is it would allow easy and simple stacking of each parameter in the client display without string parsing. Here's an example of what I mean:

The field might look like this:
`"cue_string" : [ 'Diagnosis: E.Coli', 'Species: Squirrel OR Raccoon', 'State: Wisconsin OR Michigan']`

Which would make a dead simple display, creating a new line for each item in that array. Otherwise, one long string would be difficult to parse reliably and display in a reasonable way.

**Comment by BlakeDraper** [comment]
An alternative to one field with string array could also be a `[field]_string` field for each of the params (except the `event_affected_count`), but the single field would be easier.

**Comment by BlakeDraper** [comment]
@aaronstephenson friendly bump on this one. I just need to know if this is in the cards or if I should write out the logic to form the display strings on the client. Doing so on the client will require requesting the lookup tables when the notifications component is initialized (in order to match the names of the ID values) - which is currently not needed, then a looping for each parameter to form a string for each. 

Seems like this could be more efficiently done as part of the logic that creates these records on the backend, but tell me what you think.

**Comment by aaronstephenson** [comment]
Yes, I can do this on the back end. I'll try for the array of field and params.

**Comment by aaronstephenson** [comment]
Implemented as `cue_strings` (notice the plural) in d73ba084

Example output:
![image](https://user-images.githubusercontent.com/8713712/75724826-cf44b580-5ca4-11ea-850c-388e83bbe1f6.png)

**Comment by BlakeDraper** [comment]
Thanks!
