### ISSUE TITLE
events orgs not displaying

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#338]
event orgs are not displaying on the live site

![image](https://user-images.githubusercontent.com/49287076/75186934-92117e00-570e-11ea-8d12-21905be2b448.png)

Tried both firefox and chrome. They do appear on the test site (which has the same version currently as the live site: 2.12.5)

**Comment by aaronstephenson** [comment]
Ugh. The change has been in the master branch for weeks, but never pushed to the production environment. Done now.

**Comment by BlakeDraper** [comment]
@JChipault This is fixed.
