### ISSUE TITLE
cryptic toast messages on the live site

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#339]
Instead of human-readable information displayed in the toast messages to tell a user what to do, we're getting JSON/Syntax/token errors. 

The "correct" messages are displaying on the test site so might be something with EROS blocking the right toast messages?

For example, if I leave comment type empty on the live site and hit "add comment" I get this:
![image](https://user-images.githubusercontent.com/49287076/75187343-7bb7f200-570f-11ea-8604-79d04f8822f2.png)

versus on the test site you see this:
![image](https://user-images.githubusercontent.com/49287076/75187798-7313eb80-5710-11ea-972d-a4aeb1af0a07.png)

Another example is typing in the wrong password on the live site gets you this:
![image](https://user-images.githubusercontent.com/49287076/75188617-0e599080-5712-11ea-98a6-cd7914f11d9e.png)

versus on the test site you see this:
![image](https://user-images.githubusercontent.com/49287076/75187721-46f86a80-5710-11ea-9537-8ff3f1ccbf82.png)

Here's one more that isn't human-readable on the live site, though I haven't tried it on the test site. This is when someone without permission to change an event off "complete" status tries to make that change:
![image](https://user-images.githubusercontent.com/49287076/75188497-d8b4a780-5711-11ea-928b-e75eff378c58.png)

**Comment by BlakeDraper** [comment]
Same for the Auth error. So I reckon we need to provide EROS a list of these requests and inquire as to why they have _started_ blocking the error response.

**Comment by JChipault** [comment]
another one happens if I am trying to create an event and fill out everything right EXCEPT FOR that I put my comments into the "Additional Comments" box instead of associated with one of the other 4 location comment prompts.
![image](https://user-images.githubusercontent.com/49287076/75199003-9dbd6e80-5727-11ea-9151-0bf65853f94f.png)

**Comment by BlakeDraper** [comment]
@JChipault it makes sense that you get an error because you have not provided a comment of the 4 special types, which is the business rule as we have encoded it. The message you would be seeing there if not for the current EROS problem is: "Each new_event_location requires at least one new_comment, which must be one of the following types: Site description, History, Environmental factors, Clinical signs"

Is this the correct application of the business rule?
CC: @aaronstephenson

**Comment by JChipault** [comment]
Yes, it's that human-readable version that I know I've seen in the past but is gone now that I was reporting.

**Comment by BlakeDraper** [comment]
This is resolved. My email to Derek @ EROS:

> Derek,

>Yes, this is finally resolved. Is there any reliable way to prevent such a change from happening again on the EROS end? This affects a public-facing application with a good number of users outside the USGS who rely on the data contained within. We don't want to keep tying up your inbox with these issues in the future as much as we don't want the application's users to be confused and unsatisfied. 

>Thanks for your help,
>Blake
