### ISSUE TITLE
Create user notification bugs

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices_django#351]
Tested process of creating, responding to, and approving a partner user.  Yielded 2 main issues:
1.  Messages were consistently sent to too many people for each step
2.  Initial registration of user for partner request did not insert request into 'whispers_userchangerequest' table, and ultimately did not send request message to WHISPers team.  Once record was manually inserted into 'whispers_userchangerequest', the appropriate message was sent.

**Comment by aaronstephenson** [comment]
This appears to be working. I just tried this on the test environment (with a tweak to ensure that all notifications and emails went to me, to avoid bothering other folks). All the notifications arrived, and the emails appeared in my inbox, and the User Change Request record was created:

![image](https://user-images.githubusercontent.com/8713712/77352171-cb88d980-6d0c-11ea-970e-15de646d8ca4.png)

![image](https://user-images.githubusercontent.com/8713712/77352227-de9ba980-6d0c-11ea-9855-19f0262c6783.png)

![image](https://user-images.githubusercontent.com/8713712/77352276-f1ae7980-6d0c-11ea-954d-3762be4c3a00.png)

**Comment by aaronstephenson** [comment]
Also, I just removed that tweak to the code, so any new requests will go to the intended recipients again.

**Comment by nbaertlein** [comment]
@aaronstephenson I just reran 4 new account request tests on the test site (see user id's 144, 145, 146, 147) and 1 new account did not register in the 'userchangerequest' table (and subsequent notifications).  I think it may have been due to an initial token error due to my having the web API open.  I think we can call this one closed, but I'll keep monitoring.  Below were the scenarious run:

**Test 1: Success**
Username: neilaug1
Org: Alabama Department of Agriculture & Industries
Role: partner user
Comment: “new account test”

**Test 2: Fail**
Username: neilaug2
Org: Alabama Department of Agriculture & Industries - Alabama Veterinary Diagnostic Laboratories
Role: partner manager
Comment: (left blank)
other: had initial token fail due to being logged into web API

**Test 3: Success**
Username: neilaug3	
Org: Alabama Department of Agriculture & Industries - Alabama Veterinary Diagnostic Laboratories
Role: partner manager
Comment: “new account test”

**Test 4: Success**
Username: neilaug4	
Org: Alabama Department of Agriculture & Industries - Alabama Veterinary Diagnostic Laboratories
Role: partner manager
Comment: (left blank)

**Comment by nbaertlein** [comment]
@aaronstephenson  Changes to the user change request table appear to be working and have been addressed in #380 .  The emailing of pertinent users seems to be working as well so I think this one can be closed.  Test case below went to intended parties (WHISPers admins and Partner admin):

**Test: Success**
Username: neilaug5	
Org: Woods Hole Oceanographic Institution - Woods Hole
Role: partner manager
Comment: (left blank)
