### ISSUE TITLE
Remove /whispers/ path from test environment configuration

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#352]
This was implemented only during the period where we had the notification branch in a distinct directory off the test directory. It would be good to return to accessing the test environment via `whisperstest.wim.usgs.gov` in place of the redundant `whisperstest.wim.usgs.gov/whispers` which is no longer needed.

**Comment by aaronstephenson** [comment]
Done. Any requests to `/whispers` or `/notifications` will now redirect to the root `/`
