### ISSUE TITLE
can see other people's notifications settings in my dashboard

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#354]
When I log in to my whispers admin account (jchipault), I can see a custom notification that Kim set up (whooping cranes) in along with the two notifications that I set up.
![image](https://user-images.githubusercontent.com/49287076/77438229-8ec3ed80-6db3-11ea-82b3-48e9a20f8876.png)

I think it was in a chat that Neil, Blake, and I talked about having a user's dashboard only show their personal notification triggers and NOT triggers that other people in their organization set up.

**Comment by aaronstephenson** [comment]
I don't think I was aware of that chat. What if the preferred behavior... everyone, even admins, only see their own notification preferences? Thanks.

**Comment by BlakeDraper** [comment]
Yes, all Custom notifications are strictly user-based. A user must create it to use it, and the user only sees their own - both the cue itself and the notification generated.

**Comment by aaronstephenson** [comment]
Fixed in e374a48e
