### ISSUE TITLE
dates in notifications not what expected

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#355]
The notification that I received about a new event doesn't have a date inserted (just says "event_date"):
![image](https://user-images.githubusercontent.com/49287076/77449234-b7ea7b00-6dbf-11ea-988e-54baf03547bf.png)

The notification I received about an updated event has the creation date, not the date that the event was updated:
![image](https://user-images.githubusercontent.com/49287076/77449993-ac4b8400-6dc0-11ea-834f-8258a7f07a5c.png)

**Comment by aaronstephenson** [comment]
OK, thanks. Easy fix.

**Comment by JChipault** [comment]
in the notifications spreadsheet in sharepoint, variable R could be either create date or update date -

R: Event Create Date or Event Modification Date

**Comment by aaronstephenson** [comment]
Fixed in e374a48e

**Comment by JChipault** [comment]
@aaronstephenson this one popped up again. I'm getting the create date in a notification about an event update. I'd expect 4/15 where it says 3/31:
![image](https://user-images.githubusercontent.com/49287076/79501440-a9286a00-7ff3-11ea-99c8-27b9a877abb3.png)

**Comment by aaronstephenson** [comment]
Sorry, this happened because of a big refactor I just did. Fixed now in 5c6d13c0
