### ISSUE TITLE
< and > reversed

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#358]
I set up a notification for greater than or equal to 10 affected
![image](https://user-images.githubusercontent.com/49287076/77453742-a4daa980-6dc5-11ea-8a6a-0d80d8b3087d.png)

but when it's in my list of notifications it reads as lesser than or equal to 10 affected
![image](https://user-images.githubusercontent.com/49287076/77453831-c2a80e80-6dc5-11ea-9dde-51fbd9568b08.png)

**Comment by BlakeDraper** [comment]
I can confirm that the `cue_strings` field response is wrong after a custom cue with the `event_affected_count_operator` field is created, though the actual field is accurate to what was submitted. This explains the incorrect display value. 

![image](https://user-images.githubusercontent.com/6978380/77469183-b24f5e00-6ddc-11ea-8112-2ea026429c6f.png)

**Comment by aaronstephenson** [comment]
Huh, sorry about that. Easy fix.

**Comment by aaronstephenson** [comment]
Fixed in e374a48e
