### ISSUE TITLE
Notification record not properly updating on PATCH

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#360]
You can see here: a PATCH is done to notification id 607 - the response reflects the change. 👍 

![image](https://user-images.githubusercontent.com/6978380/77564859-5f83ae00-6e91-11ea-87c5-f17e5d1fb652.png)

But then immediately following with a request for this user's notifications array, 607 has a different value. 

![image](https://user-images.githubusercontent.com/6978380/77564959-83df8a80-6e91-11ea-9432-8e2d6e005059.png)

**Comment by aaronstephenson** [comment]
Fixed in db1766da
