### ISSUE TITLE
Update Collaborator Alert comment type

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#363]
When a collaborator alert is submitted, the API assigns the comment type automatically. It is currently being set to the "Other" type rather than the "Collaborator Alert" type - maybe because the Collab Alert type was added later. 

Also, to piggyback, from Jenny:

>Can the [ ] and '' be removed from around the name on this part of the long-form of the message I received: Alert sent to: ['Jenny Chipault'].

**Comment by aaronstephenson** [comment]
@BlakeDraper one related question: would the event-level comment just be the submitted comment, or also some boilerplate like a pre-pended "Alert Collaborator: "? This is distinct from the notification subject.

**Comment by BlakeDraper** [comment]
I don't think the pre-append is needed if the comment has the appropriate type

**Comment by aaronstephenson** [comment]
Also, remind me, does the list of alerted collaborators only appear in the notification/email (like I currently have it written), or should I also include it in the comment?

**Comment by BlakeDraper** [comment]
I believe NWHC specified it would be in the email and not the comment. @JChipault is that correct?

**Comment by aaronstephenson** [comment]
Fixed in 645c1a74

**Comment by JChipault** [comment]
NWHC talked about this today and we would like the names of the people that were sent the alert put into the event comment. That way if only some collaborators received the alert via email, it'll make sense to those that didn't receive the alert when they look at the comment timeline (they won't think "woah, how did I miss that?"...  they'll know they were never sent the alert).

**Comment by aaronstephenson** [comment]
Recipient list included in comment in d1cc9c29

**Comment by JChipault** [comment]
@aaronstephenson the recipient list looks like this in the comments on the front end
![image](https://user-images.githubusercontent.com/49287076/78389395-4624e500-75a8-11ea-8bce-8c42a9532763.png)

**Comment by aaronstephenson** [comment]
I can replace the HTML break tag with `\r\n`. I had been under the impression that HTML was being rendered on the front end.

**Comment by JChipault** [comment]
this is what it looks like now:
![image](https://user-images.githubusercontent.com/49287076/78399228-23033100-75ba-11ea-83eb-c2f2eb0f7118.png)

**Comment by aaronstephenson** [comment]
`\r\n` and HTML tags like `<br />` are the only two options I have to make a line break, and for whatever reason they don't seem to render in the comments. I can't do anything more. @BlakeDraper any ideas about rendering this on the front end?

**Comment by BlakeDraper** [comment]
I'll look into it.

**Comment by JChipault** [comment]
I'm guessing we won't get line breaks, but could it say "sent" instead of "send" and also can the colon before my name in the example above not have a space before it?

**Comment by aaronstephenson** [comment]
Change to "sent" and removal of space before colon implemented in 47c7cce6
