### ISSUE TITLE
private events don't export

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#364]
For people who can see private events on their home page, can we get the exported csv to also have those private events? That way the export matches their permissions. It would also be good to have a column in the export that identifies the event as public or private - how hard is that to do?

![image](https://user-images.githubusercontent.com/49287076/77785393-1dda3b00-702a-11ea-97a0-68686c0c55ed.png)
![image](https://user-images.githubusercontent.com/49287076/77785442-34809200-702a-11ea-9e2a-f15782a73758.png)

**Comment by aaronstephenson** [comment]
Implemented in 1.5.0 226ccfc

**Comment by aaronstephenson** [comment]
Which user were you using?

**Comment by JChipault** [comment]
jchipault

**Comment by JChipault** [comment]
I could see the private event on my home page but the export did not show it at all

**Comment by aaronstephenson** [comment]
The code on the test instance is current. I just gave it a try on my local environment and it works fine, I can see both public and private events in the CSV file when I am logged in as you. I'll have to investigate on the test instance.

**Comment by aaronstephenson** [comment]
I just created a test user on the test instance to match the attributes of 'jchipault' (role 2, org 2), and I can download a CSV file containing both public and private events when logged in as that user:

![image](https://user-images.githubusercontent.com/8713712/78401266-fcdf9000-75bd-11ea-825b-f4eacb898033.png)

![image](https://user-images.githubusercontent.com/8713712/78401290-07018e80-75be-11ea-848a-e2eba80414be.png)

**Comment by JChipault** [comment]
huh, just tried again: 
![image](https://user-images.githubusercontent.com/49287076/78401772-17663900-75bf-11ea-9f6f-cc3ffec50d1d.png)

![image](https://user-images.githubusercontent.com/49287076/78401828-2baa3600-75bf-11ea-8197-38cd8e2d1769.png)

**Comment by aaronstephenson** [comment]
Weird. The code will only exclude the 'Public' field if the requesting user is either not logged in or has the Public role. Just to confirm, are you logged in when you click the Export CSV button?

**Comment by JChipault** [comment]
yup
![image](https://user-images.githubusercontent.com/49287076/78402996-35cd3400-75c1-11ea-8fd4-ec4d96645a12.png)

also, the private events shouldn't show on my home page if I'm not logged in (let alone export)

**Comment by aaronstephenson** [comment]
We are seeing very different things. When I go to whispers app when not logged in, I only see public events.

**Comment by JChipault** [comment]
Sorry, I wasn't clear. I think this quote from me is confusing: "also, the private events shouldn't show on my home page if I'm not logged in (let alone export)". I was trying to indicate that this is working correctly. I can only see and export public events when not logged in and that's appropriate.  No change needed

#362 is in reference to a partner manager who is logged in. 

This #364 ticket was opened because when I'm logged in (as whispers admin) I can see private events on my home page and in my dashboard (which is appropriate) but when I export data while logged in, the private events do not export (screen shots above).

**Comment by aaronstephenson** [comment]
@BlakeDraper After testing several scenarios, I think this is a front end bug. The request initiated when clicking the Export Data button on the home page does not include the Auth header, to the API only returns public data. The reason I was getting the private data last week when I tested this was because I was simultaneously logged into the Browsable API.

**Comment by BlakeDraper** [comment]
I will look into it.

**Comment by BlakeDraper** [comment]
So the issue here is that the export CSV button ultimately leads to this line:
`window.location.href = APP_SETTINGS.EVENTS_SUMMARIES_URL + queryString;` and there is no way to send a header with this sort of request because the browser itself is making the HTTP request.  I'm looking into refactoring the approach entirely, but some initial reading indicates there may be issues with providing a meaningful file name or even extension when processing the response.

**Comment by JChipault** [comment]
Q: what are the chances that we could also export the public vs private field as a column in the .csv now that public vs private is being displayed on the home page? This would help make sure that people don't accidentally share private info in spreadsheets.

**Comment by BlakeDraper** [comment]
@JChipault it was recently added. Once I have the fix applied to get the private events in your CSV, you'll see it.

**Comment by JChipault** [comment]
saaa-weet! thanks!

**Comment by BlakeDraper** [comment]
Fix done locally. Published soon.
