### ISSUE TITLE
dates of notifications different in email vs dashboard

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#365]
The date stamp on my email for standard notification is 3/23 at 8pm:
![image](https://user-images.githubusercontent.com/49287076/77439466-11997800-6db5-11ea-92b4-48a792ec48de.png)

But when I got to my dashboard, it's listed as a 3/24 notification:
![image](https://user-images.githubusercontent.com/49287076/77439411-021a2f00-6db5-11ea-9693-a6ba32b9e545.png)

Any chance we can sync the dates so that people don't think they are two separate notifications? Especially if you're following updates on an event, you could think that an event got updated on 3/23 and then again on 3/24.

**Comment by aaronstephenson** [comment]
It appears someone already changed the server's time zone to Central (specifically, 'America/Chicago') a few days ago. Judging by the email log time stamps and the dates on the notification records, the dates are aligning.

On the off chance that the email still reports a different date, it _could_ be something to do with the SMTP server (which is out of our control).  But I suspect the server time zone was the culprit.

So, I would say that this is now fixed. Can anyone confirm?

**Comment by JChipault** [comment]
looks good to me
