### ISSUE TITLE
The automatic notificationcuestandard records are not being created for new users

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#368]
Reported by Neil. I can confirm that that the users he created recently in the test DB (79-82) do not have any notificationcuestandard records associated as they should. Neil created them through the standard path, using the WHISPers client.

**Comment by aaronstephenson** [comment]
Ack. I put some logic in there to not create the standard notification cues for public users, forgetting that pretty much all users are public when they are created. Quick fix.

**Comment by aaronstephenson** [comment]
Fixed in 2aee4093
