### ISSUE TITLE
Cannot save search on live site

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices_django#370]
I'm logged in as a public user on the live site and cannot save a search.  The error received when attempting to save is:

Error. Search not saved. Error message: {"detail":"You do not have permission to perform this action."}

**Comment by BlakeDraper** [comment]
@aaronstephenson a public user is being prevented from saving a search. In fact, this is essentially the _only_ thing a public user can save. 

![image](https://user-images.githubusercontent.com/6978380/78831168-cd11fd00-79ae-11ea-8fe5-fb18cff0590b.png)

**Comment by aaronstephenson** [comment]
Fixed in b962790d

This _used_ to work but fell victim to the permissions refactor a while back.
