### ISSUE TITLE
not getting notifications about deletions

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#372]
In event 170880, I deleted a species of goose and also deleted an event org when I made all these other changes and I did not get notified about the deletions.

![image](https://user-images.githubusercontent.com/49287076/80513193-4e243a80-8944-11ea-8e70-c0355558bbc6.png)

**Comment by aaronstephenson** [comment]
This was fixed in 9ba5dfc2

**Comment by JChipault** [comment]
I just deleted a species and an event org (user jchipault in 170872) and did not get notified.

**Comment by aaronstephenson** [comment]
I looked through the notification table and you did receive a few notifications for Event 170872 that includes "An Event Organization was unassigned: Arkansas Game and Fish Commission - Barling" in the updates list.

But yeah, looks like the Location Species 298309 (Achilles Tang) deletion was not included. Not sure why. Our initial testing showed deletes. I'll look into it.

**Comment by aaronstephenson** [comment]
Fixed in ee6943e0

When I refactored the history processing on Friday, I overlooked LocationSpecies. Easy fix once identified.

**Comment by JChipault** [comment]
I deleted the species double-crested cormorant from 10060 and this is what I got:
![image](https://user-images.githubusercontent.com/49287076/81111029-02dccf80-8ee2-11ea-87b4-91ca52bd72d2.png)

The things I'm being notified about are not wrong, but the cormorant deletion seems to be missing

**Comment by aaronstephenson** [comment]
Fixed in e80ceecf
