### ISSUE TITLE
did not receive All Events notification about a comment

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#376]
Here's my standard notification settings:
![image](https://user-images.githubusercontent.com/49287076/81014212-16c0fc80-8e22-11ea-89fb-2dfab4177af1.png)

Here's the comment I made on event 10033 and never got a notification about:
![image](https://user-images.githubusercontent.com/49287076/81014333-47a13180-8e22-11ea-89b4-a8fbe662374a.png)

**Comment by aaronstephenson** [comment]
Fixed in c9e02b35
