### ISSUE TITLE
Breaking change in the auth response on dev server

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#377]
A breaking change has appeared in the dev server where the response from an auth request has been diminished. First image is from test server, which is the correct way (or at least what the client is expecting) and second image is what dev server is now returning, which is preventing login entirely. 

![image](https://user-images.githubusercontent.com/6978380/81944654-adc84a00-95c2-11ea-8aa6-7414db1c9060.png)

![image](https://user-images.githubusercontent.com/6978380/81944955-13b4d180-95c3-11ea-8933-8bd32cbc80aa.png)

**Comment by aaronstephenson** [comment]
Fixed in a5a53841
