### ISSUE TITLE
Various issues with creating/logging in with a new user in dev services

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#378]
May be best to do a screenshare - i get errors when creating a new user, but its created anyway, but then the username password does not work, and then I am unable to delete the user.

**Comment by BlakeDraper** [comment]
Since I was unable to create a new user, I changed the org of the affiliateTest user (role: affiliate) and I was able to do that, but now any request made with that user results in this error: 
![image](https://user-images.githubusercontent.com/6978380/81981605-25fc3300-95f6-11ea-9ee5-ee1ea67ebea2.png)


Traceback is too long to share here, as you can imagine given the recursion error. But you can see this yourself if you login with affiliateTest/dpkJ4PWpR8&St and try to get to just about any resource.

**Comment by aaronstephenson** [comment]
Infinite recursion caused by the requested org having itself as its parent org. Solution is to clean up those records in the dev DB (done just now).
