### ISSUE TITLE
collaborator alert with wrong name

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#383]
I watched Kim do a demo and she sent out a collaborator alert and I was in her collaborator circle. I received the following notification that has her comment but says it's from Robb Kaler.....
![image](https://user-images.githubusercontent.com/49287076/82670674-32d6e300-9c03-11ea-8c08-1741c1ae48e8.png)

**Comment by aaronstephenson** [comment]
Sorry about that. It appears that I re-used a variable name, which changed the value of the source variable. Fixed in 8c1a0c07
