### ISSUE TITLE
stale event notifications issuing twice

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#395]
There have been at least a couple of times that the stale event notifications have gone out twice in the same night (at two different times). Here's a screen shot from my email from Tuesday morning (6/30).

![image](https://user-images.githubusercontent.com/49287076/86389972-cd8ffc00-bc5c-11ea-8871-d0fd9ac612c7.png)

This also happened on Monday 6/15.

Any ideas?

**Comment by JChipault** [comment]
Ha! It was only after posting this that I noticed it was 5 AM and 5:33 PM... I was thinking it was all AM. So maybe it's just that some update was pushed around 5:33 PM that made the notifications go out again??

**Comment by aaronstephenson** [comment]
Yes, this will occasionally happen when the daemons are restarted.
