### ISSUE TITLE
api-docs branch: count error on /eventsummaries/get_count/

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#400]
I've noticed a lot of the requests with query params erroneously return the count for all the events in the database (in this case 8348). I tried a bunch of different query param combos that result in this response. This is just one example. There are some that seem to return a more accurate result but I have not fleshed out the deciding factor. Let me know if you need a deeper dive. 

![image](https://user-images.githubusercontent.com/6978380/86805896-f68a0580-c03d-11ea-9e58-566797536e02.png)

**Comment by aaronstephenson** [comment]
@BlakeDraper  I took a closer look at this, and I think the problem, at least in the case that you illustrate, is that there are two query params for the `affected_count` field: `affected_count__gte` and `affected_count__lte`. `affected_count` alone is simply ignored by Django. What param(s) is is client app using for the `affected_count` field?

Can you give me other examples that I can test?

**Comment by BlakeDraper** [comment]
OK I see what happened here. The client does use `affected_count__gte` and `affected_count__lte`. My saved Insomnia request was created a while ago, before that update was made. I did not catch that it was out of date. So that explains my 'example'. Before you close, I'll see if I can confirm any other erroneous responses.

**Comment by BlakeDraper** [comment]
Ok, tried a bunch. I can no longer confirm a problem here. I had at least one other embarrassing querying mistake amounting to user error. I think this one can be closed. Thanks for looking into it though.

**Comment by aaronstephenson** [comment]
No worries, your testing was an immense help!
